{% set name = "cytosim" %}
{% set version = "0.0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be8b9d7978d93c1bac0f3df172205d0bf52699b9149519800277cae8fff3b98b
build:
  skip: true  # [win]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  

requirements:
  build:
    - pip
    - cmake >=3.14
    - make 
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - libblas
    - liblapack
    - pybind11
  host:
    - pip
    - setuptools
    - python
    - libblas
    - liblapack
    - pybind11
  run:
    - python
    - libblas
    - liblapack
    - pybind11

test:
  imports:
    - cytosim
about:
  home: http://cytosim.org/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: "Cytosim: Langevin dynamics of active polymer networks"
  doc_url: https://cytosim.gitlab.io/cytosim/doc/code/doxygen/index.html
  dev_url: https://gitlab.com/f-nedelec/cytosim

extra:
  recipe-maintainers:
    - SergeDmi
